version: "3.8"
services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"
    networks:
      - spring
  eureka-server:
    build: ./eureka-server
    image: baseproject/eureka-server:latest
    container_name: eureka-server
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - spring
  user:
    build: ./user
    image: baseproject/user:latest
    container_name: user
    ports:
      - "8181:8181"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - spring
networks:
  postgres:
    driver: bridge
  spring:
    driver: bridge
volumes:
  postgres: